#install.packages("devtools")
#install.packages("fGarch")
#install.packages("kernlab", type="source")
# install.packages("kernlab")
install.packages("rugarch")
#install.packages("raster")
#install.packages("maps")
#install.packages("ggmap") 
#install.packages("fitdistrplus")